/*
 * Copyright (C) 2017 Diana Botez <dia.botez at gmail.com> - All Rights Reserved
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * Althering the content of this licence under any circumstances
 * is strictly forbidden.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */
package operationplanning.ES;

/**
 * @abstract
 *
 * @author Diana Botez <dia.botez at gmail.com>
 */
public
    class AddNewPatientPanel_ES extends javax.swing.JPanel
{

    /**
     * Creates new form AddNewPatientPanelES
     */
    public
        AddNewPatientPanel_ES()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNumberLabel = new javax.swing.JLabel();
        patientNumberTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        lastNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        medicalTeamLabel = new javax.swing.JLabel();
        medicalTeamsComboBox = new javax.swing.JComboBox<>();
        medicLabel = new javax.swing.JLabel();
        medicsComboBox = new javax.swing.JComboBox<>();
        patologyLabel = new javax.swing.JLabel();
        patologyComboBox = new javax.swing.JComboBox<>();
        surgeryLabel = new javax.swing.JLabel();
        surgeryComboBox = new javax.swing.JComboBox<>();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        patientNumberLabel.setText("Número de paciente");
        patientNumberLabel.setMaximumSize(new java.awt.Dimension(108000, 40));
        patientNumberLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        patientNumberLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        patientNumberTextField.setToolTipText("Add the patient number to be searched in the data base");
        patientNumberTextField.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        patientNumberTextField.setMinimumSize(new java.awt.Dimension(350, 30));
        patientNumberTextField.setPreferredSize(new java.awt.Dimension(350, 30));

        searchButton.setText("Buscar");

        lastNameTextField.setToolTipText("The last name of the patient");
        lastNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        lastNameTextField.setMinimumSize(new java.awt.Dimension(350, 30));
        lastNameTextField.setPreferredSize(new java.awt.Dimension(350, 30));

        lastNameLabel.setText("Apellido");
        lastNameLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        lastNameLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        lastNameLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        firstNameLabel.setText("Nombre");
        firstNameLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        firstNameLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        firstNameLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        firstNameTextField.setToolTipText("The first name of the patient");
        firstNameTextField.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        firstNameTextField.setMinimumSize(new java.awt.Dimension(350, 30));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(350, 30));

        medicalTeamLabel.setText("Equipo médico");
        medicalTeamLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        medicalTeamLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        medicalTeamLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        medicalTeamsComboBox.setMaximumRowCount(20);
        medicalTeamsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico dirigir 1", "Médico dirigir 2", "Médico dirigir 3", "Médico dirigir 4", "Médico dirigir 5" }));
        medicalTeamsComboBox.setToolTipText("The medical team leader");
        medicalTeamsComboBox.setMaximumSize(new java.awt.Dimension(32767, 40));
        medicalTeamsComboBox.setMinimumSize(new java.awt.Dimension(350, 30));
        medicalTeamsComboBox.setPreferredSize(new java.awt.Dimension(350, 30));

        medicLabel.setText("Médico");
        medicLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        medicLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        medicLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        medicsComboBox.setMaximumRowCount(20);
        medicsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Médico 1", "Médico 2", "Médico 3", "Médico 4" }));
        medicsComboBox.setToolTipText("The medic inside the team selected above");
        medicsComboBox.setMaximumSize(new java.awt.Dimension(32767, 40));
        medicsComboBox.setMinimumSize(new java.awt.Dimension(350, 30));
        medicsComboBox.setPreferredSize(new java.awt.Dimension(350, 30));

        patologyLabel.setText("Patología");
        patologyLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        patologyLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        patologyLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        patologyComboBox.setMaximumRowCount(20);
        patologyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patology 1", "Patology 2", "Patology 3" }));
        patologyComboBox.setToolTipText("The medical team leader");
        patologyComboBox.setMaximumSize(new java.awt.Dimension(32767, 40));
        patologyComboBox.setMinimumSize(new java.awt.Dimension(350, 30));
        patologyComboBox.setPreferredSize(new java.awt.Dimension(350, 30));

        surgeryLabel.setText("Operación quirúrgica");
        surgeryLabel.setMaximumSize(new java.awt.Dimension(200, 40));
        surgeryLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        surgeryLabel.setPreferredSize(new java.awt.Dimension(150, 30));

        surgeryComboBox.setMaximumRowCount(20);
        surgeryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operación 1", "Operación 2", "Operación 3" }));
        surgeryComboBox.setToolTipText("The medic inside the team selected above");
        surgeryComboBox.setMaximumSize(new java.awt.Dimension(32767, 40));
        surgeryComboBox.setMinimumSize(new java.awt.Dimension(350, 30));
        surgeryComboBox.setPreferredSize(new java.awt.Dimension(350, 30));

        resetButton.setText("Reiniciar");

        saveButton.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(medicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medicsComboBox, 0, 376, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(medicalTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medicalTeamsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(searchButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(resetButton)
                                .addComponent(surgeryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(patologyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patologyComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(surgeryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalTeamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicalTeamsComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicsComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patologyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patologyComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surgeryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(surgeryComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel medicLabel;
    private javax.swing.JLabel medicalTeamLabel;
    private javax.swing.JComboBox<String> medicalTeamsComboBox;
    private javax.swing.JComboBox<String> medicsComboBox;
    private javax.swing.JLabel patientNumberLabel;
    private javax.swing.JTextField patientNumberTextField;
    private javax.swing.JComboBox<String> patologyComboBox;
    private javax.swing.JLabel patologyLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> surgeryComboBox;
    private javax.swing.JLabel surgeryLabel;
    // End of variables declaration//GEN-END:variables
}
