/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operationplanning;

import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;

/**
 * @abstract
 *
 * @author Diana Botez
 */
public
    class DoctorTeamPanel_ES extends javax.swing.JPanel
{
    private
        MyUneditableTableModel doctorTeamTableModelES;
    private
        MyUneditableTableModel teamPlaningTableModelES;

    private
        DefaultComboBoxModel morningStartTimeTableModel;
    private
        DefaultComboBoxModel morningEndTimeTableModel;

    private
        JComboBox morningStartTimeTableComboBox = new JComboBox();
    private
        JComboBox morningEndTimeTableComboBox = new JComboBox();

    private
        Utils.UserType currentUserType;
    private
        Users userInstance = Users.GetInstance();

    /**
     * Creates new form mydoctorTeamPanel
     */
    public
        DoctorTeamPanel_ES(Utils.UserType userType)
    {
        currentUserType = userType;

        this.morningStartTimeTableModel = TimeTableModels.getMorningTimeTableModel();
        this.morningEndTimeTableModel = TimeTableModels.getMorningTimeTableModel();

        this.doctorTeamTableModelES = new MyUneditableTableModel(
            new String[]{"Apellidos", "Nombre", "Servicio"},
            7)
        //<editor-fold defaultstate="collapsed" desc="set column classes">
        {
            @Override
            public
                Class getColumnClass(int col)
            {
                return java.lang.String.class;
            }
        } //</editor-fold>
            ;
        this.teamPlaningTableModelES = new MyUneditableTableModel(
            new String[]{"Fecha", "Quirófano", "Hora de inicio", "Hora de finalización"},
            7)
        //<editor-fold defaultstate="collapsed" desc="set column classes">
        {
            @Override
            public
                Class getColumnClass(int col)
            {
                if (col == 0) {
                    return java.util.Date.class;
                }
                else {
                    return java.lang.String.class;
                }
            }
        } //</editor-fold>           
            ;

        morningStartTimeTableComboBox.setModel(morningStartTimeTableModel);
        morningEndTimeTableComboBox.setModel(morningEndTimeTableModel);

        morningStartTimeTableComboBox.setSelectedItem("8:00");
        morningEndTimeTableComboBox.removeItemAt(0);
        morningEndTimeTableComboBox.setSelectedItem("15:00");

        /*Call initComponents method*/
        initComponents();

        /*Update column types with morningStartTimeTableComboBox menu*/
        TableColumn startTimeColumn = teamPlaningTable.getColumnModel().getColumn(2);
        startTimeColumn.setCellEditor(new DefaultCellEditor(morningStartTimeTableComboBox));
        TableColumn endTimeColumn = teamPlaningTable.getColumnModel().getColumn(3);
        endTimeColumn.setCellEditor(new DefaultCellEditor(morningEndTimeTableComboBox));

        if (currentUserType.equals(Utils.UserType.MEDIC)) {
            addDoctorButton.setEnabled(false);
            deleteTeamButton.setEnabled(false);
            removeDoctorTeamButton.setEnabled(false);
            saveTeamButton.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        doctoresLabel = new javax.swing.JLabel();
        doctorTeamScrollPanel = new javax.swing.JScrollPane();
        doctorTeamTable = new javax.swing.JTable();
        quirofanosUtilisadoLabel = new javax.swing.JLabel();
        teamPlaningScrollPane = new javax.swing.JScrollPane();
        teamPlaningTable = new javax.swing.JTable();
        doctorTeamsubPanel = new javax.swing.JPanel();
        deleteTeamButton = new javax.swing.JButton();
        saveTeamButton = new javax.swing.JButton();
        addDoctorButton = new javax.swing.JButton();
        removeDoctorTeamButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 480));

        doctoresLabel.setText("Doctores");

        doctorTeamTable.setModel(doctorTeamTableModelES);
        doctorTeamTable.setToolTipText("");
        doctorTeamTable.setColumnSelectionAllowed(true);
        doctorTeamTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        doctorTeamTable.setName(""); // NOI18N
        doctorTeamTable.setSelectionBackground(new java.awt.Color(162, 164, 196));
        doctorTeamTable.setSelectionForeground(new java.awt.Color(75, 70, 70));
        doctorTeamTable.getTableHeader().setReorderingAllowed(false);
        doctorTeamScrollPanel.setViewportView(doctorTeamTable);

        quirofanosUtilisadoLabel.setText("Quirófanos utilizado");

        teamPlaningTable.setModel(teamPlaningTableModelES);
        teamPlaningTable.setColumnSelectionAllowed(true);
        teamPlaningTable.setDragEnabled(true);
        teamPlaningScrollPane.setViewportView(teamPlaningTable);

        deleteTeamButton.setText("Borrar equipo");
        deleteTeamButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteTeamButtonActionPerformed(evt);
            }
        });

        saveTeamButton.setText("Guardar");
        saveTeamButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                saveTeamButtonActionPerformed(evt);
            }
        });

        addDoctorButton.setText("Añadir médico");
        addDoctorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                addDoctorButtonActionPerformed(evt);
            }
        });

        removeDoctorTeamButton.setText("Borrar médico");

        javax.swing.GroupLayout doctorTeamsubPanelLayout = new javax.swing.GroupLayout(doctorTeamsubPanel);
        doctorTeamsubPanel.setLayout(doctorTeamsubPanelLayout);
        doctorTeamsubPanelLayout.setHorizontalGroup(
            doctorTeamsubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorTeamsubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteTeamButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeDoctorTeamButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDoctorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveTeamButton)
                .addContainerGap())
        );
        doctorTeamsubPanelLayout.setVerticalGroup(
            doctorTeamsubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorTeamsubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(deleteTeamButton)
                .addComponent(removeDoctorTeamButton)
                .addComponent(addDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveTeamButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teamPlaningScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
            .addComponent(doctorTeamScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(doctoresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(quirofanosUtilisadoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doctorTeamsubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(doctoresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorTeamScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quirofanosUtilisadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamPlaningScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doctorTeamsubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteTeamButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deleteTeamButtonActionPerformed
    {//GEN-HEADEREND:event_deleteTeamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTeamButtonActionPerformed

    private void saveTeamButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveTeamButtonActionPerformed
    {//GEN-HEADEREND:event_saveTeamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveTeamButtonActionPerformed

    private void addDoctorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addDoctorButtonActionPerformed
    {//GEN-HEADEREND:event_addDoctorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDoctorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JButton deleteTeamButton;
    private javax.swing.JScrollPane doctorTeamScrollPanel;
    private javax.swing.JTable doctorTeamTable;
    private javax.swing.JPanel doctorTeamsubPanel;
    private javax.swing.JLabel doctoresLabel;
    private javax.swing.JLabel quirofanosUtilisadoLabel;
    private javax.swing.JButton removeDoctorTeamButton;
    private javax.swing.JButton saveTeamButton;
    private javax.swing.JScrollPane teamPlaningScrollPane;
    private javax.swing.JTable teamPlaningTable;
    // End of variables declaration//GEN-END:variables
}
