/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operationplanning;

import java.util.Calendar;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.table.DatePickerCellEditor;

/**
 * @abstract
 *
 * @author Diana Botez
 */
public class OperationRoomPanel_EN extends javax.swing.JPanel {

    private DefaultTableModel operationRoomTableModelES;
    private DefaultComboBoxModel morningStartTimeTableModel;
    private DefaultComboBoxModel morningEndTimeTableModel;

    private JComboBox morningStartTimeTableComboBox = new JComboBox();
    private JComboBox morningEndTimeTableComboBox = new JComboBox();

    /**
     * Creates new form OperationRoomPanelES
     */
    public OperationRoomPanel_EN() {
        // <editor-fold defaultstate="collapsed" desc="Initialize variables">
        operationRoomTableModelES = new DefaultTableModel(
                new String[]{"Date", "Starting hour", "Ending hour"},
                0) //<editor-fold defaultstate="collapsed" desc="set column classes">
        {
            @Override
            public Class getColumnClass(int col) {
                String name = operationRoomTableModelES.getColumnName(col);

                if (name.equals("Date")) {
                    return java.util.Date.class;
                } else {
                    return java.lang.String.class;
                }
            }
        } //</editor-fold>
                ;

        this.morningStartTimeTableModel = TimeTableModels.getMorningTimeTableModel();
        this.morningEndTimeTableModel = TimeTableModels.getMorningTimeTableModel();

        morningStartTimeTableComboBox.setModel(morningStartTimeTableModel);
        morningStartTimeTableComboBox.setSelectedIndex(0);

        morningEndTimeTableComboBox.setModel(morningEndTimeTableModel);
        morningEndTimeTableComboBox.removeItemAt(0);
        morningEndTimeTableComboBox.setSelectedItem("15:00");
        //</editor-fold>

        /*Call initComponents method*/
        initComponents();

        // <editor-fold defaultstate="collapsed" desc="Update column types and editors">
        TableColumn dateColumn = operationRoomTable.getColumn("Date");
        dateColumn.setCellEditor(new DatePickerCellEditor());

        TableColumn startTimeColumn = operationRoomTable.getColumn("Starting hour");
        startTimeColumn.setCellEditor(new DefaultCellEditor(morningStartTimeTableComboBox));

        TableColumn endTimeColumn = operationRoomTable.getColumn("Ending hour");
        endTimeColumn.setCellEditor(new DefaultCellEditor(morningEndTimeTableComboBox));
        
        Calendar c = Calendar.getInstance();
        c.set(2017, 2, 15);
        operationRoomTableModelES.addRow(new Object[]{c.getTime(), "8:35", "12:05"});
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operationRoomScrollPane = new javax.swing.JScrollPane();
        operationRoomTable = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(640, 480));

        operationRoomTable.setModel(operationRoomTableModelES);
        operationRoomScrollPane.setViewportView(operationRoomTable);

        addButton.setText("Add");

        removeButton.setText("Remove");

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(operationRoomScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(operationRoomScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JScrollPane operationRoomScrollPane;
    private javax.swing.JTable operationRoomTable;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables


}
