
package operationplanning;

import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 * @abstract 
 * 
 * @author user
 */
public class Planning_EN extends javax.swing.JFrame {
    
    private final
        JPanel doctorTeamPanel[] = new JPanel[Utils.MAX_NUMBER_OF_TEAMS];
    private final
        JScrollPane operationRoomPanel[] = new JScrollPane[Utils.MAX_NUMBER_OF_OR];

    private final
        AddNewPatientPanel_EN addNewPatientPanel;
    private final
        AddPatientListPanel_EN addPatientListPanel;
    private final
        CreateSchedulePanel_EN createSchedulePanel;
    private final
        ModifySchedulePanel_EN modifySchedulePanel;

    /** Creates new form Antenna */
    public Planning_EN() {
        // <editor-fold defaultstate="collapsed" desc="Initialize variables">
        for (int i = 0; i < Utils.MAX_NUMBER_OF_TEAMS; i++) {
            doctorTeamPanel[i] = new DoctorTeamPanel_EN();
        }
        for (int i = 0; i < Utils.MAX_NUMBER_OF_OR; i++) {
            operationRoomPanel[i] = new OperationRoomPanel_EN();
        }

        addNewPatientPanel = new AddNewPatientPanel_EN();
        addPatientListPanel = new AddPatientListPanel_EN();
        createSchedulePanel = new CreateSchedulePanel_EN();
        modifySchedulePanel = new ModifySchedulePanel_EN();
        // </editor-fold> 

        /*Call initComponents method*/
        initComponents();
        
        // <editor-fold defaultstate="collapsed" desc="Add tabs to main panel">
        for (int i = 0; i < Utils.doctorTeamsNumber; i++) {
            doctorTeamTabbedPanel.addTab("Doctor team " + (i + 1), doctorTeamPanel[i]);
        }
        for (int i = 0; i < Utils.operatingRoomNumber; i++) {
            OperationRoomTabbedPanel.addTab("Operation room " + (i + 1), operationRoomPanel[i]);
        }

        addPatientTabbedPanel.addTab("Add new patient", addNewPatientPanel);
        addPatientTabbedPanel.addTab("Add list of patients", addPatientListPanel);

        scheduleTabbedPanel.addTab("Create schedule", createSchedulePanel);
        scheduleTabbedPanel.addTab("Modify schedule", modifySchedulePanel);
        // </editor-fold> 

        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPanel = new javax.swing.JTabbedPane();
        doctorTeamTabbedPanel = new javax.swing.JTabbedPane();
        addPatientTabbedPanel = new javax.swing.JTabbedPane();
        OperationRoomTabbedPanel = new javax.swing.JTabbedPane();
        scheduleTabbedPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPEP [EN]");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));

        jTabbedPanel.setMinimumSize(new java.awt.Dimension(640, 480));
        jTabbedPanel.setPreferredSize(new java.awt.Dimension(640, 480));

        doctorTeamTabbedPanel.setAutoscrolls(true);
        jTabbedPanel.addTab("Doctor teams", null, doctorTeamTabbedPanel, "");
        jTabbedPanel.addTab("Add new patient(s)", addPatientTabbedPanel);
        jTabbedPanel.addTab("OR time table", OperationRoomTabbedPanel);
        jTabbedPanel.addTab("Schedule", scheduleTabbedPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane OperationRoomTabbedPanel;
    private javax.swing.JTabbedPane addPatientTabbedPanel;
    private javax.swing.JTabbedPane doctorTeamTabbedPanel;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JTabbedPane scheduleTabbedPanel;
    // End of variables declaration//GEN-END:variables
    
}
