package operationplanning;

import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 * @abstract
 *
 * @author user
 */
public
    class Planning_EN extends javax.swing.JFrame
{

    private static
        Vector<DoctorTeamPanel_EN> doctorTeamPanels;
    private static
        Vector<OperationRoomPanel_EN> operationRoomPanel;

    private static
        AddNewPatientPanel_EN addNewPatientPanel;
    private static
        AddPatientListPanel_EN addPatientListPanel;
    private static
        CreateSchedulePanel_EN createSchedulePanel;
    private static
        ModifySchedulePanel_EN modifySchedulePanel;

    private
        Utils.UserType currentUserType;

    /**
     * Creates new form Antenna
     *
     * @param userType
     */
    public
        Planning_EN(Utils.UserType userType)
    {
        // <editor-fold defaultstate="collapsed" desc="Initialize variables">

        this.doctorTeamPanels = new Vector<>(Utils.MAX_NUMBER_OF_TEAMS);
        this.operationRoomPanel = new Vector<>(Utils.MAX_NUMBER_OF_OR);
        
        currentUserType = userType;

        for (int i = 0; i < Utils.doctorTeamsNumber; i++) {
            doctorTeamPanels.addElement(new DoctorTeamPanel_EN(currentUserType, i));
        }
        for (int i = 0; i < Utils.operatingRoomNumber; i++) {
            operationRoomPanel.addElement(new OperationRoomPanel_EN());
        }

        addNewPatientPanel = new AddNewPatientPanel_EN();
        addPatientListPanel = new AddPatientListPanel_EN();
        createSchedulePanel = new CreateSchedulePanel_EN();
        modifySchedulePanel = new ModifySchedulePanel_EN();
        // </editor-fold> 

        /*Call initComponents method*/
        initComponents();

        // <editor-fold defaultstate="collapsed" desc="Add tabs to main panel">
        for (int i = 0; i < Utils.doctorTeamsNumber; i++) {
            doctorTeamTabbedPanel.addTab("Doctor team " + (i + 1), doctorTeamPanels.get(i));
        }
        for (int i = 0; i < Utils.operatingRoomNumber; i++) {
            OperationRoomTabbedPanel.addTab("Operation room " + (i + 1), operationRoomPanel.get(i));
        }

        addPatientTabbedPanel.addTab("Add new patient", addNewPatientPanel);
        addPatientTabbedPanel.addTab("Add list of patients", addPatientListPanel);

        scheduleTabbedPanel.addTab("Create schedule", createSchedulePanel);
        scheduleTabbedPanel.addTab("Modify schedule", modifySchedulePanel);
        // </editor-fold> 

        pack();
    }

    public static void removeDoctorTeam(int index)
    {
        int i=0;
        doctorTeamPanels.remove(index);
        for (DoctorTeamPanel_EN team : doctorTeamPanels) {
            team.UpdateTeamPannelIndex(i++);
        }
        jTabbedPanel.repaint();
    }
        
        
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanel = new javax.swing.JTabbedPane();
        doctorTeamTabbedPanel = new javax.swing.JTabbedPane();
        addPatientTabbedPanel = new javax.swing.JTabbedPane();
        OperationRoomTabbedPanel = new javax.swing.JTabbedPane();
        scheduleTabbedPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPEP [EN]");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(740, 580));
        setPreferredSize(new java.awt.Dimension(740, 580));

        jTabbedPanel.setMinimumSize(new java.awt.Dimension(640, 480));
        jTabbedPanel.setPreferredSize(new java.awt.Dimension(640, 480));

        doctorTeamTabbedPanel.setAutoscrolls(true);
        jTabbedPanel.addTab("Doctor teams", null, doctorTeamTabbedPanel, "");
        jTabbedPanel.addTab("Add new patient(s)", addPatientTabbedPanel);
        jTabbedPanel.addTab("OR time table", OperationRoomTabbedPanel);
        jTabbedPanel.addTab("Schedule", scheduleTabbedPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane OperationRoomTabbedPanel;
    private javax.swing.JTabbedPane addPatientTabbedPanel;
    private javax.swing.JTabbedPane doctorTeamTabbedPanel;
    private static javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JTabbedPane scheduleTabbedPanel;
    // End of variables declaration//GEN-END:variables

}
