/*
 * Copyright (C) 2017 Diana Botez <dia.botez at gmail.com> - All Rights Reserved
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * Althering the content of this licence under any circumstances
 * is strictly forbidden.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */
package operationplanning.mainFiles;

import operationplanning.ES.Planning_ES;
import operationplanning.EN.Planning_EN;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import operationplanning.commonFiles.Users;
import operationplanning.commonFiles.Utils;

/**
 * @abstract
 *
 * @author user
 */
public
    class WelcomeForm_EN_ES extends javax.swing.JFrame
{

    private
        Users userInstance = Users.GetInstance();

    private
        Utils.UserType currentUser;

    /**
     * Creates new form
     */
    public
        WelcomeForm_EN_ES()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeFormPanel = new javax.swing.JPanel();
        enToggleButton = new javax.swing.JToggleButton();
        esToggleButton = new javax.swing.JToggleButton();
        logInLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        passPasswordField = new javax.swing.JPasswordField();
        approveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome! Bienvenido!");
        setResizable(false);

        enToggleButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        enToggleButton.setText("Welcome !");
        enToggleButton.setToolTipText("Select if you want to use the  app in English");
        enToggleButton.setActionCommand("Welcome");
        enToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.red, java.awt.Color.darkGray, java.awt.Color.lightGray));
        enToggleButton.setBorderPainted(false);
        enToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enToggleButtonActionPerformed(evt);
            }
        });

        esToggleButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        esToggleButton.setSelected(true);
        esToggleButton.setText("Bienvenido !");
        esToggleButton.setToolTipText("Selecciona si quieres usar la aplicación en Espaniol");
        esToggleButton.setActionCommand("Bienvenido");
        esToggleButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.pink, java.awt.Color.green, java.awt.Color.magenta), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.orange, java.awt.Color.blue, java.awt.Color.cyan)));
        esToggleButton.setBorderPainted(false);
        esToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        esToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esToggleButtonActionPerformed(evt);
            }
        });

        logInLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        logInLabel.setText("Log in / Iniciar sesión");

        usernameLabel.setText("User / Usuario");

        usernameLabel1.setText("Password / Contraseña");

        passPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPasswordFieldActionPerformed(evt);
            }
        });

        approveButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        approveButton.setText("Approve / Aprobar");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout welcomeFormPanelLayout = new org.jdesktop.layout.GroupLayout(welcomeFormPanel);
        welcomeFormPanel.setLayout(welcomeFormPanelLayout);
        welcomeFormPanelLayout.setHorizontalGroup(
            welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(welcomeFormPanelLayout.createSequentialGroup()
                .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(welcomeFormPanelLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(usernameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(usernameLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 184, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(enToggleButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(welcomeFormPanelLayout.createSequentialGroup()
                        .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(approveButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 241, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(logInLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(usernameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                .add(passPasswordField)))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, welcomeFormPanelLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(esToggleButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        welcomeFormPanelLayout.setVerticalGroup(
            welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(welcomeFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(esToggleButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(enToggleButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(logInLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35)
                .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(usernameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(welcomeFormPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(passPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 34, Short.MAX_VALUE)
                .add(approveButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(welcomeFormPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(welcomeFormPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enToggleButtonActionPerformed
        esToggleButton.setSelected(!(enToggleButton.isSelected()));
    }//GEN-LAST:event_enToggleButtonActionPerformed

    private void esToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esToggleButtonActionPerformed
        enToggleButton.setSelected(!(esToggleButton.isSelected()));
    }//GEN-LAST:event_esToggleButtonActionPerformed

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_approveButtonActionPerformed
    {//GEN-HEADEREND:event_approveButtonActionPerformed

        /* Get credentials */
        String user = usernameTextField.getText();
        char[] charPass = passPasswordField.getPassword();
        String pass = String.copyValueOf(charPass);
        Utils.UserType userType;

        /* Check credentials */
        if (userInstance.ValidateUserName(user) != Utils.ValidateUser.VALIDATION_OK) {
            if (esToggleButton.isSelected()) {
                JOptionPane.showMessageDialog(null, "Nombre de usuario desconocido.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Unknown user name.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }

        if (userInstance.ValidateUserPassword(user, pass) == Utils.ValidateUser.WRONG_PASSWORD) {
            if (esToggleButton.isSelected()) {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta para el nombre de usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Wrong password for the user name.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }

        /* Credentials are OK -> Set usertype */
        userType = userInstance.GetUserType(user);
        if (userType.equals(Utils.UserType.UNKNOWN_TYPE)) {
            if (esToggleButton.isSelected()) {
                JOptionPane.showMessageDialog(null, "Tipo de usuario desconocido para este nombre de usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Unknown user type for this user name.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            return;
        }

        this.dispose();

        if (esToggleButton.isSelected()) {
            Planning_ES window = new Planning_ES(userType);
            window.setExtendedState(JFrame.MAXIMIZED_BOTH);
            window.setVisible(true);
//            window.setResizable(false);
        }
        else {
            Planning_EN window = new Planning_EN(userType);
            window.setExtendedState(JFrame.MAXIMIZED_BOTH);
            window.setVisible(true);
//            window.setResizable(false);
        }
    }//GEN-LAST:event_approveButtonActionPerformed

    private void passPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPasswordFieldActionPerformed
        approveButtonActionPerformed(evt);
    }//GEN-LAST:event_passPasswordFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JToggleButton enToggleButton;
    private javax.swing.JToggleButton esToggleButton;
    private javax.swing.JLabel logInLabel;
    private javax.swing.JPasswordField passPasswordField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JPanel welcomeFormPanel;
    // End of variables declaration//GEN-END:variables

}
